# order-design-concentrated
# order-design-overengineered
# order-design-flexible

sonar.projectKey=order-design-flexible2

# Order Design - Concentrated
# Order Design - Overengineered
# Order Design - Flexible

sonar.projectName=Order Design - Flexible2

# 01-concentrated
# 02-overengineered
# 03-flexible

sonar.sources=03-flexible

sonar.sourceEncoding=UTF-8

sonar.exclusions=vendor/**