#sonar.projectKey=order-design-concentrated
sonar.projectKey=order-design-overengineered

#sonar.projectName=Order Design - Concentrated
sonar.projectName=Order Design - Overengineered

#sonar.sources=01-concentrated
sonar.sources=02-overengineered

sonar.sourceEncoding=UTF-8

sonar.exclusions=vendor/**