#sonar.projectKey=order-design-concentrated
#sonar.projectKey=order-design-overengineered
sonar.projectKey=order-design-flexible

#sonar.projectName=Order Design - Concentrated
#sonar.projectName=Order Design - Overengineered
sonar.projectName=Order Design - Flexible

#sonar.sources=01-concentrated
#sonar.sources=02-overengineered
sonar.sources=03-flexible

sonar.sourceEncoding=UTF-8

sonar.exclusions=vendor/**